name: ie-bank-frontend

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  KeyVault_DEV: devious-kV1-dev
  KeyVault_UAT: devious-kV1-uat
  KeyVault_PROD: devious-kV1-prod

jobs:
  build-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: npm install, build, and test (Development)
        run: |
          npm install
          npm run build:dev ## This command will build the Vue.js app using .env.development variables

      - name: Upload artifact for deployment job (Development)
        uses: actions/upload-artifact@v4
        with:
          name: node-app-dev
          path: dist-dev/

  deploy-dev:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: build-dev
    environment:
      name: 'Development'
    outputs:
      static_webapp_url: ${{ steps.deploy-to-staticwebapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build-dev job
        uses: actions/download-artifact@v4
        with:
          name: node-app-dev

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Fetch web app token from Key Vault (Development)
        id: fetch-webappdev-token
        run: |
          static_dev=$(az keyvault secret show --vault-name ${{ env.KeyVault_DEV }} --name static-web-deployment-token --query value -o tsv) \
          && echo "static_dev=${static_dev}" >> $GITHUB_ENV

      - name: List files in the workspace (Development)
        run: ls -R

      - name: Deploy to Azure Static Web App (Development)
        id: deploy-to-staticwebapp
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.static_dev }}
          action: "upload"
          app_location: .
          output_location: dist-dev

      
  build-uat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: npm install, build, and test (UAT)
        run: |
          npm install
          npm run build:uat ## This command will build the Vue.js app using .env.uat variables

      - name: Upload artifact for deployment job (UAT)
        uses: actions/upload-artifact@v4
        with:
          name: node-app-uat
          path: dist-uat/

  deploy-uat:
    if: (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main') || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build-uat, deploy-dev]
    environment:
      name: 'UAT'
    outputs:
      static_webapp_url: ${{ steps.deploy-to-staticwebapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build-uat job
        uses: actions/download-artifact@v4
        with:
          name: node-app-uat

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Fetch web app token from Key Vault (UAT)
        id: fetch-webappuat-token
        run: |
          static_uat=$(az keyvault secret show --vault-name ${{ env.KeyVault_UAT }} --name static-web-deployment-token --query value -o tsv) \
          && echo "static_uat=${static_uat}" >> $GITHUB_ENV

      - name: List files in the workspace (UAT)
        run: ls -R

      - name: Deploy to Azure Static Web App (UAT)
        id: deploy-to-staticwebapp
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.static_uat  }}
          action: "upload"
          app_location: .
          output_location: dist-uat

  
  build-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: npm install, build, and test (PROD)
        run: |
          npm install
          npm run build:prod ## This command will build the Vue.js app using .env.prod variables

      - name: Upload artifact for deployment job (PROD)
        uses: actions/upload-artifact@v4
        with:
          name: node-app-prod
          path: dist-prod/

  deploy-prod:
    if: github.event.pull_request.base.ref == 'main' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: [build-prod, deploy-uat]
    environment:
      name: 'PROD'
    outputs:
      static_webapp_url: ${{ steps.deploy-to-staticwebapp.outputs.webapp-url }}
      
    steps:
      - name: Download artifact from build-uat job
        uses: actions/download-artifact@v4
        with:
          name: node-app-prod

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Fetch web app token from Key Vault (PROD)
        id: fetch-webappprod-token
        run: |
          static_prod=$(az keyvault secret show --vault-name ${{ env.KeyVault_PROD }} --name static-web-deployment-token --query value -o tsv) \
          && echo "static_prod=${static_prod}" >> $GITHUB_ENV

      - name: List files in the workspace (PROD)
        run: ls -R

      - name: Deploy to Azure Static Web App (PROD)
        id: deploy-to-staticwebapp
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.static_prod  }}
          action: "upload"
          app_location: .
          output_location: dist-prod


        

