name: OSSF Scorecard Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run OSSF Scorecard
        uses: ossf/scorecard-action@v2.0.6
        with:
          results_file: results.json
